Add IReadOnlyDictionary based Json serializer
FirelyTeam/firely-net-common pull request #144
Opened 2021-07-22 12:23 UTC by ewoutkramer

2021-07-22 14:02 UTC, marcovisserFurore requested changes

2021-07-22 15:18 UTC, ewoutkramer commented on src/Hl7.Fhir.Support.Poco.Tests/JsonFhirSerializationTests.cs
> +            Assert.IsFalse(contactArray[0].EnumerateObject().Any());
They gave weird assembly loading errors while debugging, so I switched back. Will try again tomorrow.

2021-08-02 13:33 UTC, ewoutkramer commented on src/Hl7.Fhir.Support.Poco.Tests/JsonFhirSerializationTests.cs
> +            Assert.IsFalse(contactArray[0].EnumerateObject().Any());
✔

2021-08-02 13:33 UTC, ewoutkramer commented on src/Hl7.Fhir.Support.Poco/Serialization/JsonSerializerOptionsExtensions.cs
> +        public static JsonSerializerOptions ForFhirCompact(this JsonSerializerOptions options, Assembly modelAssembly)
✔

2021-08-02 15:11 UTC, marcovisserFurore approved these changes

2021-12-07 17:41 UTC, merged