Five W's support
FirelyTeam/firely-net-common pull request #168
Opened 2021-11-16 10:10 UTC by itye-msft

This PR adds the first "base" properties to allow auto generating FiveWs attribute for resources.
It simply exposes a new Property called FiveWs which is a list of strings.

Once this is approved and merged, we will be able to add the codegen the ability to generate and utilize the FiveWs proportey.

2021-11-23 15:58 UTC, ewoutkramer commented
Thanks!  Is `string` the best representation here?  Or an enum with values for what, when,where,why,who?

2021-11-24 08:28 UTC, itye-msft commented
> Thanks! Is `string` the best representation here? Or an enum with values for what, when,where,why,who?
@ewoutkramer it looks like there many more values other than the Five W's.
Here is a short list we gathered quickly just to bring more clarity:

- class
- recorded
- witness
- why[x]
- identifier
- version
- status
- what[x]
- subject[x]
- subject
- done[x]
- actor
- where[x]
- planned
- grade
- author
- actor
- And more options...

It looks like this list is generated for each FHIR spec, and each spec may have different values there. Which mean this cannot be part of "common".
In addition, we followed the string pattern to keep it the same as other properties already present in the project, in order to work with the reflection system later.

2021-11-30 14:50 UTC, ewoutkramer commented
Ah, so this is a mapping to any of the elements in the pattern at http://hl7.org/fhir/fivews.html.

Yes - generating an enum per-version means that we could not use it from common, but (at least currently) none of the domain resources are in common.  It also depends a bit on the kind of use.  Is this for in a UI?  Or are you doing some kind of analysis on it?

2021-11-30 15:00 UTC, itye-msft commented
> Ah, so this is a mapping to any of the elements in the pattern at http://hl7.org/fhir/fivews.html.
> 
> Yes - generating an enum per-version means that we could not use it from common, but (at least currently) none of the domain resources are in common. It also depends a bit on the kind of use. Is this for in a UI? Or are you doing some kind of analysis on it?

@ewoutkramer the use case (for our case) would be to enforce a level of authorization  over entities. (e.g. a consent to view data of a patient). Having these mappings handy in the SDK would make the implementation a breeze.

Would you approve this PR?
Or would you like me to change/move the mapping to the specific R4 domain?
I thought that having it as string and use reflection, would allow it to be available to all domains.

2021-12-02 16:41 UTC, ewoutkramer commented
A string is then probably best. Shall we put `where[x]` there, or `where` ?

Will you update the code generator in cooperation with @ginocanessa?

2021-12-03 06:59 UTC, itye-msft commented
> A string is then probably best. Shall we put `where[x]` there, or `where` ?
> 
> Will you update the code generator in cooperation with @GinoCanessa?

In my team we thought where[x] is preferred in order to be aligned with the specs.
I already have a draft PR for the code gen in case this PR will be approved, with cooperation and consultation of Gino :)

2021-12-03 08:54 UTC, ewoutkramer commented
Nice! One more question: why is this an array?  Does this mean one element can play multiple role's in the "five W's"?

2021-12-03 09:00 UTC, ewoutkramer requested changes

2021-12-03 09:00 UTC, ewoutkramer commented on src/Hl7.Fhir.Support.Poco/Introspection/PropertyMapping.cs
> +        /// </summary>
```suggestion
        /// </summary>
        /// <remarks>Each string in the array represents the exact element name of one the elements of the 
        /// <c>FiveWs</c> pattern from http://hl7.org/fhir/fivews.html. Choice elements are spelled with the
        /// [x] suffix, like <c>done[x]</c>. </remarks>
```

2021-12-03 09:00 UTC, ewoutkramer commented on src/Hl7.Fhir.Support.Poco/Introspection/PropertyMapping.cs
> +        /// </summary>
Maybe even add why it repeats.

2021-12-03 15:58 UTC, itye-msft commented
> Nice! One more question: why is this an array? Does this mean one element can play multiple role's in the "five W's"?

It's actually a good question. 
I looked at random generated code using this attribute (using the draft PR for codegen) and the only places I found more than one value in the array were the following similar to this one:
It's an array because it can certainly have multiple values, for example, this is a snippet of the "future" generated code :
```[FhirElement("subject", InSummary=true, Order=150, FiveWs= new string[] {"FiveWs.subject[x]","FiveWs.subject"})]
    [CLSCompliant(false)]
    [References("Patient","Group","Device","Location")]
    [DataMember]
    public Hl7.Fhir.Model.ResourceReference Subject
    {
      get { return _Subject; }
      set { _Subject = value; OnPropertyChanged("Subject"); }
    }
```
It looks like it's used for synonym phrases. But for sure there are places where more than one option is provided by the spec, and that's why an array is presented.

2021-12-07 10:08 UTC, ewoutkramer approved these changes

2021-12-07 10:08 UTC, merged