New Poco XmlDeserializer
FirelyTeam/firely-net-common pull request #213
Opened 2022-06-29 14:21 UTC by mmsmits

Fixes: https://github.com/FirelyTeam/firely-net-sdk/issues/1948

2022-07-26 10:20 UTC, ewoutkramer commented
Our review session resulted in the following points:

* User-friendly constructors without assembly?  (ala FhirXmlParser.Parse())
* Document public methods
* Review places where we skip token (using ReadToContent, e.g. at the end of deserializeElementInto) - make sure we don't skip tokens that we should report warnings about.
* UNEXPECTED_ELEMENT is not a very useful error to report when finding an incorrect order (See file with existing error messages from the old parser).
* Use existing constants for Xml namespaces
* Handle contained resources in deserializeElementInto (about line 158 - probably the while() is only valid for non-contained-resources). This will make readDataTypeList and readResourceList obsolete (the same) - and no more special case in readSingleValue.
* Handle xmlns special case earlier - it is unnecessary to do a FindMappedElementByName
* ParsePrimitiveValue should use ELementModel.Types parsers

Also, please use as much as possible the existing texts from the error messages:

* $"The attribute '{xa.Name.LocalName}' in element '{xa.Parent.Name.LocalName}' uses the namespace '{xa.Name.NamespaceName}', which is not allowed."
* $"The attribute '{xa.Name.LocalName}' in element '{xa.Parent.Name.LocalName}' has an empty value, which is not allowed."
* $"The element '{xe.Name.LocalName}' has no namespace, expected the HL7 FHIR namespace (http://hl7.org/fhir)"
* $"The element '{xe.Name.LocalName}' uses the namespace '{xe.Name.NamespaceName}', which is not allowed."
* $"Xml node of type '{node.NodeType}' is unexpected at this point"
"The 'schemaLocation' attribute is disallowed." (was a setting whether to allow it)
* $"Element '{parent.Name().LocalName}' must have child elements and/or a value attribute"
* $"Element with name '{scanName}' was found multiple times, but not in sequence."
* $"The element '{container.Name.LocalName}' has a contained resource and therefore should not have attributes."
* $"Element '{node.Name}' is not in the correct order and should come before element '{lastName}'."

2022-07-27 13:49 UTC, ewoutkramer commented
Ah, and we still need to validate our whitespace handling/trimming!

2022-08-09 15:39 UTC, ewoutkramer requested changes

2022-08-10 08:39 UTC, mmsmits commented on src/Hl7.Fhir.Support.Poco/Serialization/DataAnnotationDeserialzationValidator.cs
> +        public void ValidateProperty(ref object? instance, in PropertyDeserializationContext context, out CodedValidationException[]? reportedErrors)
For implementers of ```IDeserializationValidator``` to be able to alter the instance during validation, like we did in ```CustomPropertyValueValidator```

2022-08-11 13:39 UTC, ewoutkramer approved these changes

2022-08-11 13:39 UTC, merged