Unify terminology interfaces
FirelyTeam/firely-net-common pull request #251
Opened 2022-11-22 10:03 UTC by ewoutkramer

(description to follow)

2022-11-22 10:05 UTC, ewoutkramer commented on src/Hl7.Fhir.Support.Poco/Specification/Terminology/ValidateCodeParameters.cs
> +        public Resource ValueSet { get; private set; }
Note that this used to be `ValueSet` - so this is a breaking change.

2022-11-22 16:57 UTC, marcovisserFurore requested changes

2022-11-22 16:57 UTC, marcovisserFurore commented on src/Hl7.Fhir.Support.Poco/Specification/Terminology/ITerminologyService.cs
> +    public interface ICodeSystemTerminologyService : ICodeValidationTerminologyService
```suggestion
    public interface ICodeSystemTerminologyService
```

2022-11-22 16:57 UTC, marcovisserFurore commented on src/Hl7.Fhir.Support.Poco/Specification/Terminology/ITerminologyService.cs
> +    public interface ICodeSystemTerminologyService : ICodeValidationTerminologyService
`ICodeSystemTerminologyService` should not be dependent on `ICodeValidationTerminologyService`

2022-11-23 08:30 UTC, marcovisserFurore approved these changes

2022-11-23 08:30 UTC, merged